# ============================================================
# AMapPlus Android Companion Build Script
# ============================================================
# Requires: JDK 8+, Android SDK, PowerShell 5.1+
# Output: E:\Project\AMap\AMap\package\AMap_yy_dd_HH_mm.apk
# ============================================================

$ErrorActionPreference = 'Stop'

$env:JAVA_HOME    = 'D:\Env\jdk11'
$env:ANDROID_HOME = 'D:\Env\android-sdk'
$env:PATH = $env:JAVA_HOME + '\bin;' + $env:PATH
$ANDROID_SDK_ROOT = $env:ANDROID_HOME

# Check-Last function (must be at top)
function Check-Last {
    param([string]$Name)
    if ($LASTEXITCODE -ne 0) { throw "$Name failed (exit $LASTEXITCODE)" }
}

# Paths
$root        = $PSScriptRoot
$buildDir    = Join-Path $root 'build'
$genDir      = Join-Path $buildDir 'gen'
$classesDir  = Join-Path $buildDir 'classes'
$dexDir      = Join-Path $buildDir 'dex'
$resDir      = Join-Path $root 'app\src\main\res'
$manifest    = Join-Path $root 'app\src\main\AndroidManifest.xml'
$keystore    = Join-Path $root 'ArcfoxS5.keystore'
$tmpDir      = Join-Path $env:LOCALAPPDATA 'Temp'

$androidJar  = 'D:\Env\android-sdk\platforms\android-31\android.jar'
$buildTools  = 'D:\Env\android-sdk\build-tools\34.0.0'
$aapt        = Join-Path $buildTools 'aapt.exe'
$d8          = Join-Path $buildTools 'd8.bat'
$r8Jar       = Join-Path $buildTools 'lib\d8.jar'   # d8.jar 内含 R8（混淆+收缩+出dex）
$zipalign    = Join-Path $buildTools 'zipalign.exe'
$apksigner   = Join-Path $buildTools 'apksigner.bat'
$proguardRules = Join-Path $root 'proguard-rules.pro'

# APK output name — force China Standard Time (GMT+8) so the timestamp is always Beijing time,
# regardless of the machine's local timezone (avoids UTC drift when building on other PCs).
$chinaTz = [System.TimeZoneInfo]::FindSystemTimeZoneById('China Standard Time')
$beijingNow = [System.TimeZoneInfo]::ConvertTimeFromUtc([System.DateTime]::UtcNow, $chinaTz)
$ts        = $beijingNow.ToString('yyyyMMdd_HHmm')
$buildTime = $beijingNow.ToString('yyyy-MM-dd HH:mm')

# Deliverable naming rule: <AppName>_<package>_<versionCode>_<yyyyMMdd_HHmm>.apk
# versionCode is parsed from AndroidManifest.xml so it can never drift from the real build.
$manifestXml  = [xml](Get-Content $manifest -Raw)
$pkgName      = $manifestXml.manifest.package
$versionCode  = $manifestXml.manifest.GetAttribute('android:versionCode')
if (-not $versionCode) { $versionCode = '0' }
$outApk    = "E:\Project\AMap\AMap\package\AMapMax_${pkgName}_${versionCode}_${ts}.apk"

# ============================================================
# Clean
# ============================================================
Write-Host 'Cleaning...'
Remove-Item $buildDir -Recurse -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Force -Path $genDir, $classesDir, $dexDir, (Split-Path $outApk -Parent) | Out-Null

# Generate BuildConfig.java (fixed build-time) into build/gen so it stays OUT of the hand-written source tree
$buildConfigPkg = Join-Path $genDir 'com\autonavi\companion\BuildConfig.java'
New-Item -ItemType Directory -Force -Path (Split-Path $buildConfigPkg -Parent) | Out-Null
$noBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllLines($buildConfigPkg, @(
    'package com.autonavi.companion;',
    '',
    '/** Auto-generated by build.ps1 - DO NOT EDIT */',
    'public final class BuildConfig {',
    "    public static final String BUILD_TIME = `"$buildTime`";",
    '    private BuildConfig() {}',
    '}'
), $noBom)
Write-Host "BuildConfig.java generated: BUILD_TIME=$buildTime"

# ============================================================
# aapt -> R.java
# ============================================================
Write-Host 'aapt (R.java)...'
& $aapt package -f -m -J $genDir -M $manifest -S $resDir -I $androidJar
Check-Last 'aapt R.java'

# ============================================================
# javac
# ============================================================
Write-Host 'javac...'

# Collect all .java source files
$srcFiles = @()
Get-ChildItem -Recurse -File (Join-Path $root 'app\src\main\java') -Filter '*.java' | ForEach-Object { $srcFiles += $_.FullName }
Get-ChildItem -Recurse -File $genDir -Filter '*.java' | ForEach-Object { $srcFiles += $_.FullName }

# Join into one line (space-separated) for .bat file
$filesLine = $srcFiles -join ' '
Write-Host "  source files: $($srcFiles.Count), filesLine length: $($filesLine.Length)"

# JDK 17 requires --release 8 (cannot use -source 8 -target 8)
# Use single-quote string concatenation to avoid double-quote escaping issues
$javacBin   = Join-Path $env:JAVA_HOME 'bin'
$javacCmd = '"' + (Join-Path $javacBin 'javac.exe') + '" --release 8 -encoding UTF-8 -classpath "' + $androidJar + '" -d "' + $classesDir + '" ' + $filesLine
Write-Host "  javacCmd length: $($javacCmd.Length)"

# Write temp .bat file (ASCII encoding to avoid UTF-8 BOM issues)
$javacBatLines = @(
    '@echo off',
    $javacCmd
)
[System.IO.File]::WriteAllLines((Join-Path $tmpDir '_javac.bat'), $javacBatLines, [System.Text.Encoding]::ASCII)
Write-Host "  javac .bat written, executing..."

# Start-Process + file redirection to avoid PowerShell capturing javac stderr
$proc = Start-Process `
    -FilePath 'cmd.exe' `
    -ArgumentList '/c', (Join-Path $tmpDir '_javac.bat') `
    -Wait -NoNewWindow -PassThru `
    -RedirectStandardError (Join-Path $tmpDir 'javac_err.txt') `
    -RedirectStandardOutput (Join-Path $tmpDir 'javac_out.txt')

$err = Get-Content (Join-Path $tmpDir 'javac_err.txt') -Raw
$out = Get-Content (Join-Path $tmpDir 'javac_out.txt') -Raw
if ($out) { Write-Host "  javac stdout: $out" }
if ($err) { Write-Host "  javac stderr: $err" }

if ($proc.ExitCode -ne 0) { throw "javac failed with exit $($proc.ExitCode)" }

# Check if .class files were generated
$expected = Get-ChildItem -Recurse -File $classesDir -Filter '*.class' | Measure-Object | Select-Object -ExpandProperty Count
if ($expected -eq 0) { throw "javac produced no class files" }
Write-Host "  ($expected class files generated)"

# ============================================================
# R8 -> classes.dex (混淆 + 收缩 + 优化)
# ============================================================
Write-Host 'R8 (minify + shrink + dex)...'
$classFiles = Get-ChildItem -Recurse -File $classesDir -Filter '*.class' | ForEach-Object { $_.FullName }
Write-Host "  class files: $($classFiles.Count)"

# 与 javac 相同的 bat 执行方式，避免 PowerShell 参数转义问题
$javaBin = Join-Path $env:JAVA_HOME 'bin'
$r8Cmd = '"' + (Join-Path $javaBin 'java.exe') + '" -cp "' + $r8Jar + '" com.android.tools.r8.R8 --release --pg-conf "' + $proguardRules + '" --lib "' + $androidJar + '" --output "' + $dexDir + '" ' + ($classFiles -join ' ')
$r8BatLines = @(
    '@echo off',
    $r8Cmd
)
[System.IO.File]::WriteAllLines((Join-Path $tmpDir '_r8.bat'), $r8BatLines, [System.Text.Encoding]::ASCII)
$r8proc = Start-Process `
    -FilePath 'cmd.exe' `
    -ArgumentList '/c', (Join-Path $tmpDir '_r8.bat') `
    -Wait -NoNewWindow -PassThru `
    -RedirectStandardError (Join-Path $tmpDir 'r8_err.txt') `
    -RedirectStandardOutput (Join-Path $tmpDir 'r8_out.txt')
$r8err = Get-Content (Join-Path $tmpDir 'r8_err.txt') -Raw
$r8out = Get-Content (Join-Path $tmpDir 'r8_out.txt') -Raw
if ($r8out) { Write-Host "  R8 stdout: $r8out" }
if ($r8err) { Write-Host "  R8 stderr: $r8err" }
if ($r8proc.ExitCode -ne 0) { throw "R8 failed with exit $($r8proc.ExitCode)" }

# R8 直接输出 classes.dex 到 dexDir
$dexFile = Join-Path $dexDir 'classes.dex'
if (-not (Test-Path $dexFile)) { throw "classes.dex not found after R8 at $dexFile" }
Write-Host "  dex: $((Get-Item $dexFile).Length) bytes"

# ============================================================
# aapt -> .apk (unsigned)
# ============================================================
Write-Host 'aapt (package APK)...'
$UnsignedApk = Join-Path $buildDir 'unsigned.apk'
& $aapt package -f -M $manifest -S $resDir -I $androidJar -F $UnsignedApk
Check-Last 'aapt package'

# Add classes.dex to APK (change to dexDir so aapt uses correct entry name)
$dexFile = Join-Path $dexDir 'classes.dex'
if (-not (Test-Path $dexFile)) { throw "classes.dex not found at $dexFile" }
Push-Location $dexDir
& $aapt add $UnsignedApk 'classes.dex'
Pop-Location
Check-Last 'aapt add classes.dex'

# ============================================================
# zipalign
# ============================================================
Write-Host 'zipalign...'
& $zipalign -f -v 4 $UnsignedApk $outApk | Out-Null
Check-Last 'zipalign'

# ============================================================
# apksigner
# ============================================================
Write-Host 'apksigner (sign)...'
& $apksigner sign --ks $keystore --ks-key-alias platform --ks-pass pass:android --key-pass pass:android $outApk
Check-Last 'apksigner'
# Remove auto-generated .idsig file (idsig not supported by this version)
$idsigFile = "$outApk.idsig"
if (Test-Path $idsigFile) { Remove-Item $idsigFile -Force }

Write-Host "Done: $outApk"
