      - name: Install Android build tools
        shell: pwsh
        run: sdkmanager "platforms;android-31" "build-tools;34.0.0"

      - name: Prepare version
        id: version
        shell: pwsh
        run: |
          $short_sha = $env:GITHUB_SHA.Substring(0,7)
          $nowUtc = (Get-Date).ToUniversalTime()
          $epoch = Get-Date "1970-01-01"
          $version_code = [Math]::Floor(($nowUtc - $epoch).TotalSeconds)
          $version_name = $nowUtc.ToString("yyyyMMdd") + "-$short_sha"
          echo "SHORT_SHA=$short_sha" >> $env:GITHUB_ENV
          echo "APP_VERSION_CODE=$version_code" >> $env:GITHUB_ENV
          echo "APP_VERSION_NAME=$version_name" >> $env:GITHUB_ENV
          echo "version_code=$version_code" >> $env:GITHUB_OUTPUT
          echo "version_name=$version_name" >> $env:GITHUB_OUTPUT
          echo "short_sha=$short_sha" >> $env:GITHUB_OUTPUT

      - name: Build signed APK
        shell: pwsh
        env:
          ANDROID_BUILD_TOOLS_VERSION: "34.0.0"
          ANDROID_PLATFORM: android-31
          APP_VERSION_CODE: ${{ steps.version.outputs.version_code }}
          APP_VERSION_NAME: ${{ steps.version.outputs.version_name }}
        run: |
          $env:ANDROID_SDK_ROOT = $env:ANDROID_HOME
          Write-Host "Detected SDK Path: $env:ANDROID_SDK_ROOT"
          .\build.ps1
